pub(crate) struct ToolSpec {
    pub id: &'static str,
    pub display_name: &'static str,
    pub category: &'static str,
    pub names: &'static [&'static str],
    pub version_args: Option<&'static [&'static str]>,
}

#[cfg(windows)]
pub(crate) fn tool_specs() -> &'static [ToolSpec] {
    WINDOWS_TOOL_SPECS
}

#[cfg(not(windows))]
pub(crate) fn tool_specs() -> &'static [ToolSpec] {
    UNIX_TOOL_SPECS
}

#[cfg(windows)]
const WINDOWS_TOOL_SPECS: &[ToolSpec] = &[
    spec(
        "git",
        "Git",
        "version_control",
        &["git.exe"],
        Some(&["--version"]),
    ),
    spec(
        "cargo",
        "Cargo",
        "runtime",
        &["cargo.exe"],
        Some(&["--version"]),
    ),
    spec(
        "rustc",
        "Rust compiler",
        "runtime",
        &["rustc.exe"],
        Some(&["--version"]),
    ),
    spec(
        "node",
        "Node.js",
        "runtime",
        &["node.exe"],
        Some(&["--version"]),
    ),
    spec("npm", "npm", "package_manager", &["npm.cmd"], None),
    spec(
        "python",
        "Python",
        "runtime",
        &["python.exe", "py.exe"],
        Some(&["--version"]),
    ),
    spec(
        "winget",
        "Windows Package Manager",
        "package_manager",
        &["winget.exe"],
        Some(&["--version"]),
    ),
    spec(
        "choco",
        "Chocolatey",
        "package_manager",
        &["choco.exe"],
        Some(&["--version"]),
    ),
    spec("scoop", "Scoop", "package_manager", &["scoop.cmd"], None),
    spec(
        "codex",
        "Codex",
        "ai_tool",
        &["codex.cmd", "codex.exe"],
        None,
    ),
    spec("grok", "Grok", "ai_tool", &["grok.exe"], None),
    spec("hermes", "Hermes", "ai_tool", &["hermes.exe"], None),
    spec("pi", "Pi", "ai_tool", &["pi.cmd", "pi.exe"], None),
    spec("gsd", "GSD", "ai_tool", &["gsd.cmd", "gsd.exe"], None),
    spec("omp", "oh-my-pi", "ai_tool", &["omp.exe"], None),
    spec("warp", "Warp", "ai_tool", &["warp.exe"], None),
    spec(
        "claude",
        "Claude",
        "ai_tool",
        &["claude.cmd", "claude.exe"],
        None,
    ),
    spec(
        "opencode",
        "OpenCode",
        "ai_tool",
        &["opencode.cmd", "opencode.exe"],
        None,
    ),
    spec("kilo", "Kilo", "ai_tool", &["kilo.cmd", "kilo.exe"], None),
    spec(
        "gemini",
        "Gemini",
        "ai_tool",
        &["gemini.cmd", "gemini.exe"],
        None,
    ),
    spec("aiup", "AIUP", "utility", &["aiup.cmd", "aiup.exe"], None),
    spec(
        "deno",
        "Deno",
        "runtime",
        &["deno.exe"],
        Some(&["--version"]),
    ),
    spec("bun", "Bun", "runtime", &["bun.exe"], Some(&["--version"])),
    spec(
        "pnpm",
        "pnpm",
        "package_manager",
        &["pnpm.cmd", "pnpm.exe"],
        None,
    ),
    spec(
        "yarn",
        "Yarn",
        "package_manager",
        &["yarn.cmd", "yarn.exe"],
        None,
    ),
    spec(
        "uv",
        "uv",
        "package_manager",
        &["uv.exe"],
        Some(&["--version"]),
    ),
    spec(
        "rustup",
        "rustup",
        "package_manager",
        &["rustup.exe"],
        Some(&["--version"]),
    ),
    spec(
        "gh",
        "GitHub CLI",
        "developer_tool",
        &["gh.exe"],
        Some(&["--version"]),
    ),
    spec(
        "pwsh",
        "PowerShell",
        "shell",
        &["pwsh.exe"],
        Some(&["--version"]),
    ),
    spec(
        "powershell",
        "Windows PowerShell",
        "shell",
        &["powershell.exe"],
        None,
    ),
];

#[cfg(not(windows))]
const UNIX_TOOL_SPECS: &[ToolSpec] = &[
    spec(
        "git",
        "Git",
        "version_control",
        &["git"],
        Some(&["--version"]),
    ),
    spec(
        "cargo",
        "Cargo",
        "runtime",
        &["cargo"],
        Some(&["--version"]),
    ),
    spec(
        "rustc",
        "Rust compiler",
        "runtime",
        &["rustc"],
        Some(&["--version"]),
    ),
    spec(
        "node",
        "Node.js",
        "runtime",
        &["node"],
        Some(&["--version"]),
    ),
    spec(
        "npm",
        "npm",
        "package_manager",
        &["npm"],
        Some(&["--version"]),
    ),
    spec(
        "python",
        "Python",
        "runtime",
        &["python3", "python"],
        Some(&["--version"]),
    ),
    spec(
        "pwsh",
        "PowerShell",
        "shell",
        &["pwsh"],
        Some(&["--version"]),
    ),
    spec(
        "brew",
        "Homebrew",
        "package_manager",
        &["brew"],
        Some(&["--version"]),
    ),
    spec(
        "port",
        "MacPorts",
        "package_manager",
        &["port"],
        Some(&["version"]),
    ),
    spec(
        "mas",
        "Mac App Store CLI",
        "package_manager",
        &["mas"],
        Some(&["version"]),
    ),
    spec(
        "softwareupdate",
        "Apple Software Update",
        "package_manager",
        &["softwareupdate"],
        None,
    ),
    spec("npx", "npx", "package_manager", &["npx"], None),
    spec(
        "pnpm",
        "pnpm",
        "package_manager",
        &["pnpm"],
        Some(&["--version"]),
    ),
    spec(
        "yarn",
        "Yarn",
        "package_manager",
        &["yarn"],
        Some(&["--version"]),
    ),
    spec("bun", "Bun", "runtime", &["bun"], Some(&["--version"])),
    spec("deno", "Deno", "runtime", &["deno"], Some(&["--version"])),
    spec("uv", "uv", "package_manager", &["uv"], Some(&["--version"])),
    spec(
        "pip",
        "pip",
        "package_manager",
        &["pip3", "pip"],
        Some(&["--version"]),
    ),
    spec("gem", "RubyGems", "package_manager", &["gem"], None),
    spec(
        "rustup",
        "rustup",
        "package_manager",
        &["rustup"],
        Some(&["--version"]),
    ),
    spec(
        "gh",
        "GitHub CLI",
        "developer_tool",
        &["gh"],
        Some(&["--version"]),
    ),
    spec("codex", "Codex", "ai_tool", &["codex"], None),
    spec("grok", "Grok", "ai_tool", &["grok"], None),
    spec("hermes", "Hermes", "ai_tool", &["hermes"], None),
    spec("pi", "Pi", "ai_tool", &["pi"], None),
    spec("gsd", "GSD", "ai_tool", &["gsd"], None),
    spec("omp", "oh-my-pi", "ai_tool", &["omp"], None),
    spec("warp", "Warp", "ai_tool", &["warp"], None),
    spec("claude", "Claude", "ai_tool", &["claude"], None),
    spec("opencode", "OpenCode", "ai_tool", &["opencode"], None),
    spec("kilo", "Kilo", "ai_tool", &["kilo"], None),
    spec("gemini", "Gemini", "ai_tool", &["gemini"], None),
    spec("aiup", "AIUP", "utility", &["aiup"], None),
    spec(
        "mise",
        "mise",
        "runtime_manager",
        &["mise"],
        Some(&["--version"]),
    ),
    spec("asdf", "asdf", "runtime_manager", &["asdf"], None),
    spec(
        "nix",
        "Nix",
        "package_manager",
        &["nix"],
        Some(&["--version"]),
    ),
    spec(
        "docker",
        "Docker",
        "container_tool",
        &["docker"],
        Some(&["--version"]),
    ),
    spec(
        "podman",
        "Podman",
        "container_tool",
        &["podman"],
        Some(&["--version"]),
    ),
    spec(
        "ollama",
        "Ollama",
        "ai_tool",
        &["ollama"],
        Some(&["--version"]),
    ),
    spec("go", "Go", "runtime", &["go"], Some(&["version"])),
    spec("java", "Java", "runtime", &["java"], Some(&["-version"])),
    spec(
        "xcodebuild",
        "Xcode",
        "developer_tool",
        &["xcodebuild"],
        Some(&["-version"]),
    ),
];

const fn spec(
    id: &'static str,
    display_name: &'static str,
    category: &'static str,
    names: &'static [&'static str],
    version_args: Option<&'static [&'static str]>,
) -> ToolSpec {
    ToolSpec {
        id,
        display_name,
        category,
        names,
        version_args,
    }
}
